DROP TABLE IF EXISTS word;

CREATE TABLE word (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    word TEXT NOT NULL,
    definition TEXT NOT NULL,
    synonym TEXT NOT NULL
);